project_id = "kai-tood"

[auth]
enabled = true
site_url = "https://kai-tood.vercel.app"
additional_redirect_urls = ["https://kai-tood.vercel.app", "https://kai-tood.vercel.app/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = true
secure_password_change = true
