"use client";

import { useActionState, useMemo, useState } from "react";
import { getThaiDistricts, getThaiSubdistricts, thaiProvinces } from "@/lib/thai-address";
import { submitMiniApplication, type MiniApplyFormState } from "./actions";

const field = "mt-2 w-full rounded-2xl border-2 border-black/10 bg-[#fffdf4] px-4 py-4 text-base font-bold outline-none transition focus:border-[#ffc400] focus:bg-white disabled:bg-black/5 disabled:text-black/40";
const locationTypes = ["ตลาด", "หน้าโรงเรียน", "ชุมชน", "โรงงาน", "ริมถนน", "ห้างสรรพสินค้า", "อื่นๆ"];
const budgets = ["ต่ำกว่า 5,000 บาท", "5,000–10,000 บาท", "10,001–20,000 บาท", "มากกว่า 20,000 บาท", "ยังไม่ได้เตรียมงบส่วนนี้"];
const terms = [
  ["term_equipment", "รับทราบว่าราคา 9,900 บาทไม่รวมอุปกรณ์ทั้งหมด"], ["term_extra_equipment", "รับทราบว่าต้องจัดหาอุปกรณ์เพิ่มเติมตามบัญชีรายการของบริษัท"], ["term_chicken_price", "รับทราบราคาไก่หมักพร้อมทอด 75 บาทต่อกิโลกรัม"], ["term_free_shipping", "รับทราบเงื่อนไขสั่งครบ 45 กิโลกรัมจึงจัดส่งฟรี"], ["term_no_exclusive", "รับทราบว่า MINI STARTER ไม่มีสิทธิ์ผูกขาดจังหวัด อำเภอ หรือเขต"], ["term_location_check", "ยินยอมให้บริษัทตรวจสอบทำเลและระยะห่างจากสาขาเดิม"], ["term_not_approved", "เข้าใจว่าการส่งใบสมัครยังไม่ถือว่าได้รับอนุมัติ"], ["term_no_payment", "ยืนยันว่าจะไม่ชำระเงินจนกว่าบริษัทแจ้งผลอนุมัติ"], ["term_privacy", "ยินยอมให้บริษัทเก็บและใช้ข้อมูลเพื่อพิจารณาใบสมัครและติดต่อกลับตามนโยบายความเป็นส่วนตัว"],
] as const;

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-[1.75rem] border border-black/10 bg-white p-5 shadow-lg shadow-black/5 sm:p-6"><h2 className="text-2xl font-black">{title}</h2><div className="mt-5 grid gap-4">{children}</div></section>; }
function Input({ label, name, type = "text", required = true, help, maxLength }: { label: string; name: string; type?: string; required?: boolean; help?: string; maxLength?: number }) { return <label className="block"><span className="text-sm font-black text-black/80">{label}{required && <span className="text-red-600"> *</span>}</span><input name={name} type={type} required={required} maxLength={maxLength} className={field} />{help && <span className="mt-1 block text-xs font-bold leading-5 text-black/50">{help}</span>}</label>; }
function Select({ label, name, options }: { label: string; name: string; options: string[] }) { return <label className="block"><span className="text-sm font-black text-black/80">{label} <span className="text-red-600">*</span></span><select name={name} required className={field}><option value="">เลือกคำตอบ</option>{options.map((o) => <option key={o} value={o}>{o}</option>)}</select></label>; }

export function MiniApplyForm() {
  const [state, action, pending] = useActionState(submitMiniApplication, { ok: false, message: "" } satisfies MiniApplyFormState);
  const [files, setFiles] = useState<File[]>([]);
  const [residenceProvince, setResidenceProvince] = useState("");
  const [residenceDistrict, setResidenceDistrict] = useState("");
  const [openingProvince, setOpeningProvince] = useState("");
  const [openingDistrict, setOpeningDistrict] = useState("");
  const [openingSubdistrict, setOpeningSubdistrict] = useState("");
  const [submissionToken] = useState(() => crypto.randomUUID());
  const residenceDistricts = getThaiDistricts(residenceProvince);
  const openingDistricts = getThaiDistricts(openingProvince);
  const openingSubdistricts = getThaiSubdistricts(openingProvince, openingDistrict);
  const previews = useMemo(() => files.map((file) => ({ name: file.name, url: URL.createObjectURL(file) })), [files]);
  if (state.ok) return <div className="rounded-[2rem] border border-green-200 bg-green-50 p-7 text-center shadow-xl">{state.referenceCode && <><p className="text-sm font-black text-green-700">เลขอ้างอิงใบสมัคร</p><h2 className="mt-2 text-4xl font-black">{state.referenceCode}</h2></>}<p className={`${state.referenceCode ? "mt-4" : ""} font-bold leading-8 text-green-900`}>{state.message}</p><div className="mt-5 rounded-2xl bg-white p-4 text-left"><p className="font-black text-green-900">ขั้นตอนต่อไป</p><p className="mt-2 text-sm font-bold leading-7 text-black/65">เพิ่ม LINE Official Account แล้วส่งชื่อ–นามสกุล พร้อมเลขอ้างอิงใบสมัคร เพื่อยืนยันว่าต้องการให้ทีมงานตรวจสอบต่อ ผู้สมัครที่ไม่ยืนยันผ่าน LINE จะยังไม่ถูกนัดพูดคุย</p></div><a href="https://line.me/R/ti/p/@kaikoy" target="_blank" rel="noreferrer" className="mt-4 inline-flex w-full justify-center rounded-full bg-[#06C755] px-6 py-4 text-lg font-black text-white">เพิ่ม LINE เพื่อรับผลสมัคร</a></div>;
  return <form action={action} className="grid gap-5 rounded-[2.25rem] border border-black/10 bg-[#fff9df] p-4 shadow-xl shadow-black/5 sm:p-6">
    <input type="hidden" name="started_at" value={Date.now()} /><input type="hidden" name="submission_token" value={submissionToken} /><input type="text" name="website" tabIndex={-1} autoComplete="off" className="hidden" />
    {state.message && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-black text-red-700">{state.message}</div>}
    <Section title="หมวดที่ 1 ข้อมูลผู้สมัคร"><Input label="ชื่อและนามสกุล" name="full_name" /><Input label="อายุ" name="age" type="number" /><Input label="หมายเลขโทรศัพท์" name="phone" type="tel" /><Input label="LINE ID" name="line_id" required={false} /><Input label="อาชีพปัจจุบัน" name="current_occupation" /><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="text-sm font-black text-black/80">จังหวัดที่พักอาศัย <span className="text-red-600">*</span></span><select name="residence_province" required value={residenceProvince} onChange={(event) => { setResidenceProvince(event.currentTarget.value); setResidenceDistrict(""); }} className={field}><option value="">เลือกจังหวัด</option>{thaiProvinces.map((province) => <option key={province} value={province}>{province}</option>)}</select></label><label className="block"><span className="text-sm font-black text-black/80">อำเภอ/เขตที่พักอาศัย <span className="text-red-600">*</span></span><select name="residence_district" required disabled={!residenceProvince} value={residenceDistrict} onChange={(event) => setResidenceDistrict(event.currentTarget.value)} className={field}><option value="">เลือกอำเภอ/เขต</option>{residenceDistricts.map((district) => <option key={district} value={district}>{district}</option>)}</select></label></div></Section>
    <Section title="หมวดที่ 2 ข้อมูลทำเล"><div className="grid gap-4 sm:grid-cols-3"><label className="block"><span className="text-sm font-black text-black/80">จังหวัดที่จะเปิดขาย <span className="text-red-600">*</span></span><select name="opening_province" required value={openingProvince} onChange={(event) => { setOpeningProvince(event.currentTarget.value); setOpeningDistrict(""); setOpeningSubdistrict(""); }} className={field}><option value="">เลือกจังหวัด</option>{thaiProvinces.map((province) => <option key={province} value={province}>{province}</option>)}</select></label><label className="block"><span className="text-sm font-black text-black/80">อำเภอ/เขต <span className="text-red-600">*</span></span><select name="opening_district" required disabled={!openingProvince} value={openingDistrict} onChange={(event) => { setOpeningDistrict(event.currentTarget.value); setOpeningSubdistrict(""); }} className={field}><option value="">เลือกอำเภอ/เขต</option>{openingDistricts.map((district) => <option key={district} value={district}>{district}</option>)}</select></label><label className="block"><span className="text-sm font-black text-black/80">ตำบล/แขวง <span className="text-red-600">*</span></span><select name="opening_subdistrict" required disabled={!openingDistrict} value={openingSubdistrict} onChange={(event) => setOpeningSubdistrict(event.currentTarget.value)} className={field}><option value="">เลือกตำบล/แขวง</option>{openingSubdistricts.map((subdistrict) => <option key={subdistrict} value={subdistrict}>{subdistrict}</option>)}</select></label></div><Input label="ที่อยู่หรือชื่อสถานที่" name="location_address" maxLength={500} /><Input label="สถานที่หรือพิกัดโดยประมาณ" name="location_description" maxLength={500} help="พิมพ์ชื่อสถานที่ จุดสังเกต หรือวางลิงก์ Google Maps ก็ได้ เช่น หน้า CJ อำเภอเมืองนครสวรรค์" /><Input label="ลิงก์ Google Maps (ถ้ามี)" name="google_maps_url" required={false} maxLength={500} /><Select label="ประเภททำเล" name="location_type" options={locationTypes} /><Input label="ค่าเช่าต่อเดือน" name="monthly_rent" required={false} /><Input label="ช่วงเวลาที่วางแผนเปิดขาย" name="planned_opening_period" /><Input label="คู่แข่งใกล้เคียง" name="nearby_competitors" required={false} /><label><span className="text-sm font-black">รูปภาพทำเล (ไม่บังคับ)</span><input name="location_photos" type="file" accept="image/jpeg,image/png,image/webp" multiple className={field} onChange={(e) => setFiles(Array.from(e.currentTarget.files ?? []))} /><span className="mt-1 block text-xs font-bold text-black/50">หากมี สามารถแนบรูปเพื่อช่วยให้ทีมงานพิจารณาทำเลได้ หากยังไม่มีรูป สามารถข้ามได้ รองรับ JPG, PNG, WebP ขนาดไม่เกิน 5MB ต่อไฟล์</span></label>{previews.length > 0 && <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{previews.map((p) => <img key={p.url} src={p.url} alt={p.name} className="h-32 rounded-2xl object-cover" />)}</div>}</Section>
    <Section title="หมวดที่ 3 ความพร้อม"><Select label="ขณะนี้มีทำเลแล้วหรือยัง" name="has_location" options={["มีทำเลแล้ว", "กำลังเจรจา", "ยังไม่มีทำเล"]} /><Input label="ใครจะเป็นผู้ลงมือขายจริง" name="actual_seller" /><Input label="คาดว่าจะพร้อมเปิดขายเมื่อใด" name="ready_to_open" /><Select label="เคยขายอาหารหรือทำธุรกิจมาก่อนหรือไม่" name="food_business_experience" options={["เคยขายอาหาร", "เคยทำธุรกิจอื่น", "ไม่เคยมาก่อน"]} /><Input label="รายละเอียดประสบการณ์" name="experience_details" required={false} /><label className="flex gap-3 rounded-2xl bg-[#fffdf4] p-4 font-bold"><input name="can_follow_online_course" value="true" type="checkbox" required className="h-6 w-6 accent-[#ffc400]" />สามารถเรียนคอร์สออนไลน์และทำตามระบบแบรนด์ได้</label><Select label="มีงบจัดหาอุปกรณ์เพิ่มเติมและทุนหมุนเวียนเท่าใด" name="extra_budget_range" options={budgets} /></Section>
    <Section title="หมวดที่ 4 การยอมรับเงื่อนไข">{terms.map(([name, label]) => <label key={name} className="flex gap-3 rounded-2xl bg-[#fffdf4] p-4 font-bold leading-7"><input name={name} value="true" type="checkbox" required className="mt-1 h-6 w-6 shrink-0 accent-[#ffc400]" />{label}</label>)}</Section>
    <div className="rounded-2xl border-2 border-[#06C755]/25 bg-[#06C755]/10 p-4 text-center">
      <p className="font-black text-[#087a3d]">ขั้นตอนรับผลสมัครทาง LINE</p>
      <p className="mt-2 text-sm font-bold leading-7 text-black/65">กรอกข้อมูลและกดส่งใบสมัครให้สำเร็จก่อน ระบบจะแสดงเลขอ้างอิงและปุ่มเพิ่ม LINE <span className="font-black text-black">@kaikoy</span> กรุณาส่งชื่อ–นามสกุลพร้อมเลขอ้างอิงทาง LINE เพื่อยืนยันการสมัคร</p>
    </div>
    <button disabled={pending} aria-disabled={pending} className="min-h-14 rounded-full bg-[#ffc400] px-6 py-4 text-lg font-black text-black shadow-lg shadow-yellow-300/30 disabled:opacity-60">{pending ? "กำลังส่งข้อมูล..." : "ส่งใบสมัคร MINI STARTER"}</button>
  </form>;
}
