import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";
import { BRAND_NAME, BRAND_SUBTITLE } from "@/lib/brand";
import { miniStarterPackage } from "@/lib/franchise-packages";
import { MiniApplyForm } from "./mini-apply-form";

const included = ["เคาน์เตอร์ Mini พร้อมป้ายแบรนด์ตามแบบ", "ถาดใส่ไก่ จำนวน 10 ใบ", "ทัพพีตักไก่", "ถ้วยตวงสำหรับไก่และข้าวเหนียว", "เครื่องชั่งดิจิทัล", "บัญชีรายการวัสดุและอุปกรณ์มาตรฐานที่ผู้สมัครต้องจัดหาเพิ่มเติมด้วยตนเอง", "คอร์สออนไลน์สอนการทอดไก่ การนึ่งข้าวเหนียว การเตรียมสินค้า การคำนวณต้นทุน และการเปิดขาย", "สิทธิ์ซื้อไก่หมักพร้อมทอด ราคา 75 บาทต่อกิโลกรัม", "สั่งไก่หมักพร้อมทอดครบ 45 กิโลกรัม จัดส่งฟรี", "สามารถขออัปเกรดเป็นชุดแฟรนไชส์มาตรฐานภายหลังได้ตามเงื่อนไขของบริษัท"];
const warnings = ["ราคา 9,900 บาทไม่รวมอุปกรณ์ทุกอย่างที่ใช้เปิดร้าน", "ผู้สมัครต้องมีงบสำหรับจัดหาอุปกรณ์เพิ่มเติม วัตถุดิบ ค่าเช่า และเงินทุนหมุนเวียน", "MINI STARTER ไม่ใช่การนำชุดแฟรนไชส์มาตรฐานมาลดราคา", "MINI STARTER ไม่มีสิทธิ์ผูกขาดระดับจังหวัด อำเภอ หรือเขต", "การกรอกใบสมัครยังไม่ถือว่าได้รับสิทธิ์", "ห้ามชำระเงินจนกว่าบริษัทจะแจ้งผลอนุมัติ"];

export default function ApplyMiniPage() {
  return <main className="min-h-dvh bg-white text-black"><header className="border-b border-black/10 bg-white/95"><nav className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-3 sm:px-6 lg:px-8"><Link href="/" className="flex min-w-0 items-center gap-3 rounded-2xl focus-ring"><BrandLogo size={54} priority /><div className="min-w-0"><div className="truncate text-lg font-black">{BRAND_NAME}</div><div className="truncate text-xs font-bold text-black/55">{BRAND_SUBTITLE}</div></div></Link><Link href="/franchise/apply" className="shrink-0 rounded-full bg-black px-4 py-3 text-sm font-black text-white focus-ring">สมัครชุดมาตรฐาน</Link></nav></header>
    <section className="mx-auto grid max-w-6xl gap-8 px-4 py-8 sm:px-6 sm:py-12 lg:grid-cols-[0.82fr_1.18fr] lg:px-8"><aside className="space-y-5 lg:sticky lg:top-6 lg:self-start"><div className="overflow-hidden rounded-[2.25rem] bg-black text-white shadow-2xl shadow-black/20"><div className="p-6 sm:p-8"><div className="inline-flex rounded-full bg-[#ffc400] px-4 py-2 text-sm font-black text-black">สมัครแฟรนไชส์ MINI STARTER</div><h1 className="mt-5 text-4xl font-black leading-tight sm:text-5xl">เหนียวไก่เยอะโคตร MINI STARTER</h1><p className="mt-4 text-base font-bold leading-8 text-white/72">รูปแบบร้านขนาดเล็ก สำหรับผู้ที่ต้องการทดลองทำเลและเริ่มสร้างยอดขายในพื้นที่ใหม่</p><div className="mt-6 rounded-[1.5rem] bg-white p-5 text-black"><p className="text-sm font-black text-black/55">ราคาแพ็กเกจ</p><p className="text-4xl font-black text-[#E60012]">9,900 บาท</p><p className="mt-2 font-black">ไก่หมักพร้อมทอด 75 บาท/กก. • ครบ 45 กก. ส่งฟรี</p></div></div><div className="bg-[#fff9df] p-4"><img src={miniStarterPackage.image} alt={miniStarterPackage.imageAlt} className="max-h-[70vh] min-h-52 w-full rounded-[1.5rem] bg-white object-contain shadow-inner shadow-black/5" /></div></div><div className="rounded-[1.5rem] border border-red-200 bg-red-50 p-5"><h2 className="text-xl font-black text-red-700">ข้อควรรู้ก่อนสมัคร</h2><ul className="mt-3 grid gap-2 text-sm font-bold leading-7 text-red-950">{warnings.map((w) => <li key={w}>• {w}</li>)}</ul></div></aside>
      <div className="space-y-5"><section className="rounded-[1.5rem] border border-black/10 bg-[#fff9df] p-5"><h2 className="text-2xl font-black">สิ่งที่ได้รับ</h2><ul className="mt-4 grid gap-2 font-bold leading-7 text-black/70">{included.map((item) => <li key={item}>✓ {item}</li>)}</ul></section><section className="rounded-[1.5rem] border border-black/10 bg-white p-5"><h2 className="text-2xl font-black">พื้นที่เปิดสาขา</h2><p className="mt-2 font-bold leading-7 text-black/65">บริษัทจะตรวจสอบพิกัดและระยะห่างจากสาขาเดิมก่อนอนุมัติทุกครั้ง พื้นที่ที่แจ้งด้านล่างใช้สำหรับแจ้งเตือนและคัดกรองเบื้องต้นเท่านั้น ไม่ปฏิเสธอัตโนมัติโดยดูเพียงชื่อจังหวัด ต้องตรวจสอบอำเภอ เขต แขวง ตำบล และพิกัดจริงด้วย</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#fff9df] p-4"><b>กรุงเทพมหานคร</b><p className="mt-2 text-sm font-bold leading-7">เขตจตุจักร, เขตตลิ่งชัน, เขตบางกะปิ และพื้นที่ใกล้เคียงที่อาจทับซ้อนกับสาขาเดิม</p></div><div className="rounded-2xl bg-[#fff9df] p-4"><b>ต่างจังหวัด</b><p className="mt-2 text-sm font-bold leading-7">อินทร์บุรี สิงห์บุรี, ชะอำ เพชรบุรี, ไชยา สุราษฎร์ธานี, บางปะกง ฉะเชิงเทรา, หาดใหญ่ สงขลา, ศรีราชา ชลบุรี, ตลาดสะพานดำและพื้นที่คุ้มครองเดิม นครสวรรค์</p></div></div></section><section className="rounded-[1.5rem] border border-black/10 bg-white p-5"><h2 className="text-2xl font-black">MINI STARTER ต่างจากชุดมาตรฐาน</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-black/10 p-4"><b>MINI STARTER</b><p className="mt-2 text-sm font-bold text-black/60">เริ่มเล็ก ทดลองทำเล อุปกรณ์และสิทธิ์จำกัด ไม่มีผูกขาดพื้นที่</p></div><div className="rounded-2xl border border-black/10 p-4"><b>แฟรนไชส์ชุดมาตรฐาน</b><p className="mt-2 text-sm font-bold text-black/60">รายละเอียดอุปกรณ์และสิทธิ์ต่างกัน แยกแบบฟอร์มสมัครชัดเจน</p><Link href="/franchise/apply" className="mt-3 inline-flex font-black text-[#E60012]">ไปหน้าสมัครชุดมาตรฐาน →</Link></div></div></section><a href="#mini-form" className="inline-flex w-full justify-center rounded-full bg-[#ffc400] px-6 py-4 text-lg font-black shadow-lg shadow-yellow-300/30">กรอกใบสมัคร MINI STARTER</a><div id="mini-form"><MiniApplyForm /></div></div></section></main>;
}
