import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getCurrentProfile, isOwner } from "@/lib/auth";
import { createKpiSupabaseAdminClient } from "@/lib/kpi-supabase";
import { generateContentCaption } from "@/lib/ai-caption";

type MediaRow={storage_bucket:string|null;storage_path:string|null}; type Row={id:string;source_type:string|null;source_work_date:string|null;caption_status:string;caption_text:string|null;publish_status:string;work_submission_media:MediaRow|MediaRow[]|null};
async function regenerate(formData:FormData){"use server";const profile=await getCurrentProfile();if(!isOwner(profile))redirect("/dashboard");const id=String(formData.get("id")??"");const kpi=createKpiSupabaseAdminClient();if(!kpi||!id)redirect("/content-ready?ai=failed");try{const {data:row,error}=await kpi.from("content_automation_queue").select("source_type,source_work_date,work_submission_media(storage_bucket,storage_path)").eq("id",id).eq("owner_status","approved").maybeSingle();if(error||!row)throw error??new Error("ไม่พบรายการ");const raw=row.work_submission_media as MediaRow|MediaRow[]|null;const media=Array.isArray(raw)?raw[0]??null:raw;let url:null|string=null;if(media?.storage_path&&row.source_type!=="video"){const {data:s}=await kpi.storage.from(media.storage_bucket??"employee-footage").createSignedUrl(media.storage_path,600);url=s?.signedUrl??null;}const caption=await generateContentCaption({imageUrl:url,sourceType:row.source_type,workDate:row.source_work_date});await kpi.from("content_automation_queue").update({caption_text:caption,caption_status:"ready",updated_at:new Date().toISOString()}).eq("id",id);revalidatePath("/content-ready");redirect("/content-ready?ai=success");}catch(e){console.error("regenerate caption failed",e);redirect("/content-ready?ai=failed");}}
export default async function Page({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){const profile=await getCurrentProfile();if(!isOwner(profile))redirect("/dashboard");const kpi=createKpiSupabaseAdminClient();if(!kpi)return <main className="p-4">ไม่พบการเชื่อมต่อ KPI</main>;const p=searchParams?await searchParams:{};const ai=typeof p.ai==="string"?p.ai:"";const {data,error}=await kpi.from("content_automation_queue").select("id,source_type,source_work_date,caption_status,caption_text,publish_status,work_submission_media(storage_bucket,storage_path)").eq("owner_status","approved").order("owner_reviewed_at",{ascending:false}).limit(30);if(error)return <main className="p-4">โหลดไม่สำเร็จ: {error.message}</main>;const rows=(data??[]) as Row[];const cards=await Promise.all(rows.map(async r=>{const m=Array.isArray(r.work_submission_media)?r.work_submission_media[0]??null:r.work_submission_media;if(!m?.storage_path)return{...r,url:null};const{data:s}=await kpi.storage.from(m.storage_bucket??"employee-footage").createSignedUrl(m.storage_path,3600);return{...r,url:s?.signedUrl??null};}));return <main className="mx-auto w-full max-w-xl space-y-4 px-3 py-4 pb-24"><header className="rounded-3xl border bg-white p-4 shadow-sm"><p className="text-xs font-bold text-red-600">OWNER • CONTENT</p><h1 className="text-2xl font-black">แคปชัน AI รอตรวจ</h1><p className="text-sm text-black/55">AI เขียนให้ • คุณตรวจและอนุมัติก่อนโพสต์</p><div className="mt-3 inline-flex rounded-2xl bg-black px-4 py-2 font-black text-white">{cards.length} รายการ</div></header>{ai==="success"?<div className="rounded-2xl bg-green-50 p-3 font-bold text-green-800">สร้างแคปชันใหม่เรียบร้อย</div>:null}{ai==="failed"?<div className="rounded-2xl bg-red-50 p-3 font-bold text-red-800">AI สร้างแคปชันไม่สำเร็จ กรุณาลองอีกครั้ง</div>:null}{cards.map(i=><article key={i.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="bg-black">{i.url?(i.source_type==="video"?<video src={i.url} controls playsInline className="max-h-[70vh] w-full object-contain"/>:<img src={i.url} alt="Content" className="max-h-[70vh] w-full object-contain"/>):null}</div><div className="space-y-3 p-4"><div className="flex justify-between text-xs font-bold text-black/50"><span>{i.source_type==="video"?"🎬 คลิป":"📷 รูป"}</span><span>{i.caption_status==="ready"?"AI พร้อม":"รอ AI"}</span></div>{i.caption_text?<div className="whitespace-pre-wrap rounded-2xl bg-black/[.04] p-4 text-[15px] leading-7">{i.caption_text}</div>:<div className="rounded-2xl bg-amber-50 p-4 text-sm font-bold text-amber-800">ยังไม่มีแคปชัน AI</div>}<form action={regenerate}><input type="hidden" name="id" value={i.id}/><button className="w-full rounded-2xl border border-black/15 bg-white px-4 py-3 font-black">{i.caption_text?"ให้ AI เขียนใหม่":"สร้างแคปชันด้วย AI"}</button></form><p className="text-center text-xs text-black/45">สถานะโพสต์: {i.publish_status} • ยังไม่โพสต์จริง</p></div></article>)}</main>}
